- name: play level variables
  hosts: local
  connection: local
  tasks:
  - name: print course details
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Course Name: {{ COURSE }}"