- name: demo on conditions
  hosts: local
  connection: local
  vars:
   IS_LIVE: false
  tasks:
  - name: print it is Liv or not
    ansible.builtin.debug:
     msg: "Yes ,it is Live"
    when: IS_LIVE