- name: Demo on Condition
  hosts: local
  connection: local
  vars:
  COURSE: "Ansible"
  IS_LIVE: true
  tasks:
  - name: check live is there or not
    ansible.builtin.debug:
      msg: "Yes it is Live, Course: {{COURSE}}"
    when: IS_LIVE