- name: check number is less than number 10 or not
  hosts: local
  connection: local
  vars:
  NUMBER_OF_SESSIONS: 6
  tasks:
  - name: check if ansible is more than 5 sessions
  ansible.builtin.debug:
     msg: "Yes number of sessions is more than 10"
     when: NUMBER_OF_SESSIONS > 10 