- name: print the diff between command and shell in ansible
  hosts: local
  connection: local
  tasks:
    - name:  command module test
      #ansible.builtin.command: cat /etc/passwd | grep root | command 
      #register: command_output
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: user_output
 
    - name: print shell output
      ansible.builtin.debug:
        msg: "{{ user_output.stdout }}"
      
    - name: command module test  
      ansible.builtin.shell:  ls -ltr > fileoutput.txt
      register: file_output

    - name: print file output
      ansible.builtin.debug:
        msg: "{{ file_output.stdout }}"