- name:  Demo for installing pkg using ansible"
  hosts: local
  connection: local
  tasks:
    - name: install the packages
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
         - nginx
         - nodejs
         - zip
        

        