- name: Installing package through advanced loop
  hosts: local
  connection: local
  become: yes
  tasks:

  hosts: local
  connection: local
  tasks:
    - name: install the packages
      ansible.builtin.package:
        name: "{{item.name}}"
        state: "{{item.state}}"
      loop:
         - { name: "nginx", state: "present" }  # name is key state is value or # map/dic
         - { name: "nodejs", state: "present" }
         - { name: "zip",    state: "present" }